env:
  jest/globals: true
plugins:
  - node
  - promise
  - jest
extends:
  - standard
  - plugin:node/recommended
  - plugin:promise/recommended
  - plugin:jest/recommended
rules:
  no-param-reassign: error
  no-empty: warn
  node/no-unpublished-require: 0
  jest: true