language: node_js

node_js:
  - 10.13.0

# services:
#   - mongodb

cache:
  directories:
  - node_modules

git:
  depth: 3

script:
  - jest --coverage --coverageReporters=text-lcov | coveralls && rm -rf ./coverage